version: 2.1


defaults: &defaults
  docker:
    - image: circleci/node:13.8.0


jobs:
  build:
     <<: *defaults
     steps:
      - checkout
      - run: npm i
      - run: npm run lint


  test:
     <<: *defaults
     steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
     <<: *defaults
     steps:
      - checkout
      - run: npm audit


workflows:
  build-test-analyze-job:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
